### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by nonnontrivial** [Botmock/botmock-rasa-export#19]
**Is your feature request related to a problem? Please describe.**
The docs should show sample output, provide links to find data for the `.env` file, and break down steps for contributing.

**Describe the solution you'd like**
- [ ] shows sample output
- [ ] `.env` setup
- [ ] "How to Contribute" section

**Comment by NikV** [comment]
@nonnontrivial Got this just about ready in the help center docs! Going to try to work on it in the context now of Github as well.

**Comment by nonnontrivial** [comment]
@NikV now that https://github.com/Botmock/botmock-rasa-export/pull/20 has landed, this should be ready to add.
