### ISSUE TITLE
Bug: Responses contain text from connected nodes

### ISSUE THREAD

**Issue by ortsaCniveK** [Botmock/botmock-rasa-export#34]
## Description
When exporting, responses contain text from nodes that are "next" in the series.  Because of the way that Rasa uses response variations, this will lead to unwanted behavior -- for a given node A, you may get responses from next node B, which essentially "skips ahead" in a series of nodes.

## Command that led to error
`npm start` (with `useNodeNameForResponses == true`)

## Example
![Input node](https://user-images.githubusercontent.com/20219677/94621813-db5a1b00-0265-11eb-901d-ac1aa57cb368.png)
![Input flow](https://user-images.githubusercontent.com/20219677/94621820-de550b80-0265-11eb-8c64-89e64cb42ea0.png)
![Resulting utterance](https://user-images.githubusercontent.com/20219677/94621831-e44aec80-0265-11eb-8e27-c6c4fd4cdb7a.png)
![Related story](https://user-images.githubusercontent.com/20219677/94621834-e57c1980-0265-11eb-9282-faff04c9dd5a.png)

## Desired behavior
Only include response text and response text variations for a given node.

**Comment by Gauhar** [comment]
@ortsaCniveK  - We are able to reproduce this and in process of fixing this issue. Thank you for your patience..

**Comment by Gauhar** [comment]
@ortsaCniveK  - This is also fixed and newer version is published

**Comment by Gauhar** [comment]
Thank you so much for your patience.
