### ISSUE TITLE
Nodes that already contain "utter_" should not have "utter_" prefixed

### ISSUE THREAD

**Issue by ortsaCniveK** [Botmock/botmock-rasa-export#35]
## Description
Nodes may or may not already contain "utter_", but when exported all responses generated are prefixed with `utter_`.

## Command that led to bug
`npm start` (with `useNodeNameForResponses == true`)

## Example
![Input node](https://user-images.githubusercontent.com/20219677/94622175-91256980-0266-11eb-90ea-df7ed22956bc.png)
![Resulting utterance](https://user-images.githubusercontent.com/20219677/94622179-94205a00-0266-11eb-8cb1-c2942345973e.png)

## Desired Behavior
Do not prefix nodes that already have `utter_` with `utter_`.

**Comment by Gauhar** [comment]
@ortsaCniveK  - We in process of fixing this. Thank you for your patience.

**Comment by Gauhar** [comment]
@ortsaCniveK  - We have fixed the issue and a newer version is published.
Please pull from master and follow the steps below
`git pull origin master`
`rm -rf node_modules && rm package-lock.json && npm i`
Update the env file if you would like to and then
`npm run start`
